name: Generate ERD
on:
  pull_request:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Install xmllint
      run: sudo apt-get install -y graphviz

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: generate ERD
      env: 
        PG_HOST: ${{ secrets.RDS_STAGING_HOST }}
        PG_DB: postgres
        PG_USER: ${{ secrets.RDS_STAGING_USER }}
        PG_PASSWORD: ${{ secrets.RDS_STAGING_PASSWORD }}
        PG_PORT: 5432
        BASE_URL: ${{ secrets.BASE_URL }}
      run: python app/scripts/erd_gen.py

    - name: commit ERD
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "update ERD" -a

    - name: push changes
      continue-on-error: true
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
